#pragma once
#include "../../../Parser/AST/C-AST-Nodes/C-ASTNodeUtilities/C-ASTExpressionTypes.h"

extern const char *tokenTypeStr[];
extern const char *tokenTypeToSymbol[];

typedef enum {
    IDENTIFIER, 
    CONSTANT,
    LONG_CONSTANT,
    INT_KEYWORD,
    LONG_KEYWORD,
    VOID_KEYWORD,
    STATIC_KEYWORD,
    EXTERN_KEYWORD,
    RETURN_KEYWORD,
    SWITCH_KEYWORD,
    DEFAULT_KEYWORD,
    CASE_KEYWORD,
    OPEN_PAREN,
    CLOSE_PAREN,
    OPEN_BRACE,
    CLOSE_BRACE,
    SEMICOLON,
    TILDE,
    HYPHEN,
    TWO_PLUS,
    TWO_HYPHENS,
    PLUS, 
    ASTERISK,
    SLASH,
    PERCENT,
    EXCLAMATION,
    TWO_AMPERSANDS,
    TWO_BARS,
    ONE_EQUAL,
    TWO_EQUALS,
    NOT_EQUAL,
    LESS_THAN,
    GREATER_THAN,
    LESS_EQUAL,
    GREATER_EQUAL,
    PLUS_EQUAL,
    MINUS_EQUAL,
    STAR_EQUAL,
    SLASH_EQUAL,
    PERCENT_EQUAL,
    AMPERSAND,
    BAR,
    CARET,
    LEFT_SHIFT,
    RIGHT_SHIFT,
    AMPERSAND_EQUAL,
    BAR_EQUAL,
    CARET_EQUAL,
    LEFT_SHIFT_EQUAL,
    RIGHT_SHIFT_EQUAL,
    IF_KEYWORD,
    ELSE_KEYWORD,
    QUESTION_MARK,
    COMMA,
    LEXER,
    WHILE_KEYWORD,
    FOR_KEYWORD,
    DO_KEYWORD,
    COLON,
    BREAK_KEYWORD,
    CONTINUE_KEYWORD,
    ERROR,
    NOT_ACCEPTING
} TokenType;

typedef enum {
    KEYWORD_TOKEN_INT,
    KEYWORD_TOKEN_LONG,
    KEYWORD_TOKEN_VOID,
    KEYWORD_TOKEN_STATIC,
    KEYWORD_TOKEN_DEFAULT,
    KEYWORD_TOKEN_CASE,
    KEYWORD_TOKEN_EXTERN,
    KEYWORD_TOKEN_RETURN,
    KEYWORD_TOKEN_SWITCH,
    KEYWORD_TOKEN_IF,
    KEYWORD_TOKEN_ELSE,
    KEYWORD_TOKEN_WHILE,
    KEYWORD_TOKEN_FOR,
    KEYWORD_TOKEN_DO,
    KEYWORD_TOKEN_BREAK,
    KEYWORD_TOKEN_CONTINUE,
    KEYWORD_TOKEN_END_OF_KEYWORDS
} KeywordTokenType;

typedef enum {
    SINGLE_CHAR_TOKEN_OPEN_PAREN,
    SINGLE_CHAR_TOKEN_CLOSE_PAREN,
    SINGLE_CHAR_TOKEN_OPEN_BRACE,
    SINGLE_CHAR_TOKEN_CLOSE_BRACE,
    SINGLE_CHAR_TOKEN_SEMICOLON,
    SINGLE_CHAR_TOKEN_TILDE,
    SINGLE_CHAR_TOKEN_HYPHEN,
    SINGLE_CHAR_TOKEN_PLUS,
    SINGLE_CHAR_TOKEN_ASTERISK,
    SINGLE_CHAR_TOKEN_SLASH,
    SINGLE_CHAR_TOKEN_PERCENT,
    SINGLE_CHAR_TOKEN_EXCLAMATION,
    SINGLE_CHAR_TOKEN_ONE_EQUAL,
    SINGLE_CHAR_TOKEN_LESS_THAN,
    SINGLE_CHAR_TOKEN_GREATER_THAN,
    SINGLE_CHAR_TOKEN_AMPERSAND,
    SINGLE_CHAR_TOKEN_BAR,
    SINGLE_CHAR_TOKEN_CARET,
    SINGLE_CHAR_TOKEN_QUESTION_MARK,
    SINGLE_CHAR_TOKEN_COMMA,
    SINGLE_CHAR_TOKEN_COLON,
    SINGLE_CHAR_END_OF_SINGLE_CHAR_TOKENS
} SingleCharTokenType;

typedef enum {
    TWO_CHAR_TOKEN_TWO_AMPERSANDS,
    TWO_CHAR_TOKEN_TWO_BARS,
    TWO_CHAR_TOKEN_LEFT_SHIFT,
    TWO_CHAR_TOKEN_RIGHT_SHIFT,
    TWO_CHAR_END_OF_TWO_CHAR_TOKENS
} TwoCharTokenType;

TokenType keywordTokenTypeToTokenType(KeywordTokenType type);
TokenType singleCharTokenTypeToTokenType(SingleCharTokenType type);
TokenType twoCharTokenTypeToTokenType(TwoCharTokenType type);

int isTokenTypeBinaryOp(TokenType type);
int isTokenTypeUnaryOp(TokenType type);
TokenType binaryOpToOpWithEqual(TokenType type);
TokenType subAddtoDoubleSubAdd(TokenType type);
char* tokenTypeToToken(TokenType type);
unaryType tokenTypeToUnaryType(TokenType type);
unaryType prefixToPostfix(unaryType type);